# All constants in one place for clarity

require_relative 'vector2d'


BOARD_WIDTH = 50
BOARD_HEIGHT = 15
UNSAFE_BOARD_WIDTH = BOARD_WIDTH - 1
BOARD_EXTENDED_WIDTH = BOARD_WIDTH + 3

OUT_OF_BOUNDS_COLOR = -1
NUMBER_OF_EMPTY_COLORS = 8
NUMBER_OF_TELEPORTER_COLORS = 4
NUMBER_OF_TRAP_COLORS = 2
NUMBER_OF_WALL_COLORS = 2
TELEPORT_DISTANCE = 4
TELEPORT_WIDTH = 2*TELEPORT_DISTANCE+1


NUMBER_OF_COLORS = NUMBER_OF_EMPTY_COLORS + NUMBER_OF_TELEPORTER_COLORS + NUMBER_OF_TRAP_COLORS + NUMBER_OF_WALL_COLORS

NUMBER_OF_TURNS = 10000
NUMBER_OF_BOARDS = 20

INITIAL_SPECIMENS = 15
SPECIMEN_LIFESPAN = 100
REPRODUCTION_RATE = 10
NUMBER_OF_PARENTS = 2

GENOME_LENGTH = 100
GENOME_MAX_VALUE = (1 << GENOME_LENGTH) - 1
GENOME_CROSSOVER_RATE = 0.05
GENOME_MUTATION_RATE = 0.01

VISION_DISTANCE = 2
VISION_WIDTH = 2*VISION_DISTANCE+1
VISION = []
(-VISION_DISTANCE..VISION_DISTANCE).each{|x|
    (-VISION_DISTANCE..VISION_DISTANCE).each{|y|
        VISION.push(Vector2D.new(x,y))
    }
}

MOVES = []
(-1..1).each{|x|
    (-1..1).each{|y|
        MOVES.push(Vector2D.new(x,y))
    }
}

RANDOM_SEED = 13722829
